### ISSUE TITLE
Dress icon

### ISSUE THREAD

**Issue by bhousel** [ideditor/temaki#50]
for `craft=dressmaker` or maybe other specific kinds of `shop=clothing`  (wedding?)

**Comment by quincylvania** [comment]
This turned into two icons 😄

<img width="181" alt="Screen Shot 2020-01-07 at 1 18 59 PM" src="https://user-images.githubusercontent.com/2046746/71918485-59aee400-3150-11ea-8e9f-9945da385fc2.png">
<img width="182" alt="Screen Shot 2020-01-07 at 1 19 12 PM" src="https://user-images.githubusercontent.com/2046746/71918487-5ae01100-3150-11ea-960c-ce5f5cb03c3c.png">
