### ISSUE TITLE
Missing icon: Advertising board

### ISSUE THREAD

**Issue by forteller** [ideditor/temaki#57]
I'd love to see an icon for this! https://wiki.openstreetmap.org/wiki/Tag:advertising=board
It's missing an icon both when searching for it in the list of elements to add, and in the element marker on the map itself.

Thanks a lot! :)

**Comment by quincylvania** [comment]
Hi @forteller, we've recently added an icon for this but it hasn't been released yet.

<img width="185" alt="image" src="https://user-images.githubusercontent.com/2046746/75311284-206b2a00-580b-11ea-8090-e472037d64ff.png">

https://ideditor.github.io/temaki/docs/#icon-temaki-bulletin_board
