### ISSUE TITLE
Icon size 50x50?

### ISSUE THREAD

**Issue by plepe** [ideditor/temaki#59]
Hi!

I noticed that many icons have the size 50x50, whereas most icons (and also the icons of the original Maki icon set) have 15x15. Is there are reason? Are there plans to unify the size of the icons?

Examples:
* chairlift.svg
* abseiling.svg

**Comment by plepe** [comment]
Just noticed. Apparently these are the icons which were imported in #2.

**Comment by quincylvania** [comment]
> Just noticed. Apparently these are the icons which were imported in #2.

@plepe Yep. While we aim for 15x15, we didn't bother to rescale the ones from that import. We don't have plans to do so unless someone really needs it. I'd welcome a PR for it.

As a workaround when rendering these on the web, you can set the width and height of the container in CSS and the browser should scale down the icon proportionally. That's what we do in iD.
