### ISSUE TITLE
Add icon search to gallery page

### ISSUE THREAD

**Issue by quincylvania** [ideditor/temaki#61]
Temaki now has over 460 icons! This is fantastic, but can make it tough to find what you're looking for. We should add search terms for the icons and a search field to quickly filter them.

**Comment by quincylvania** [comment]
I added search and categories! There's always room for improvement, but even a basic implementation goes a long way here.

The category data comes from a new [data/icons.json](https://github.com/ideditor/temaki/blob/master/data/icons.json) file, which is validated and embedded upon building. It takes a bit of a hack to make svg-sprite embed the data directly in the page, but it's better than loading the data file after the fact in JavaScript and dealing with CORS.

<img width="1009" alt="Screen Shot 2020-06-13 at 5 35 08 PM" src="https://user-images.githubusercontent.com/2046746/84579535-77861200-ad9c-11ea-88f9-e533d34f65df.png">
<img width="1008" alt="Screen Shot 2020-06-13 at 5 35 24 PM" src="https://user-images.githubusercontent.com/2046746/84579536-78b73f00-ad9c-11ea-9e9c-b635b3615dda.png">

**Comment by bhousel** [comment]
Whoa this looks amazing! 👏

**Comment by quincylvania** [comment]
I did a bit of followup styling…

<img width="1280" alt="Screen Shot 2020-06-15 at 10 57 36 AM" src="https://user-images.githubusercontent.com/2046746/84672908-10c93b80-aef7-11ea-9116-65049b25d5f7.png">
