### ISSUE TITLE
revise medical cross icons

### ISSUE THREAD

**Issue by ArloJamesBarnes** [ideditor/temaki#62]
specifically, `temaki-briefcase_cross`, `temaki-mountain_rescue`, and `temaki-vending_medicine`; the use of a Greek cross, crescent moon, or lozenge in relation to medicine refers exclusively to the activities of the International Committee of the Red Cross/Crescent/Crystal.

Instead, Temaki should do as various other medical practitioners do and use either the star of life (a six-armed asterisk with similar proportions of length to thickness of the arms as the cross does) or the rod of Asclepius (a snake wrapped around a staff, not to be confused with the Caduceus or staff of Hermes the messenger, which is two snakes wrapped around a winged staff and represents commerce).

I can mock up example replacements later, just wanted to get the issue up while it was on my mind.

edit: I forgot about this until I came upon my working files again. Here's the mockup:
![staroflife](https://user-images.githubusercontent.com/634501/103164102-1071fd00-47c4-11eb-8fb5-a9685e5fb882.png) @quincylvania

**Comment by quincylvania** [comment]
@ArloJamesBarnes I'd forgotten about this too 😅

Sounds reasonable to add Star of Life variants for medical icons, but I'd also leave the existing icons since some Temaki users might prefer them.

**Comment by ArloJamesBarnes** [comment]
That's fine, then it's their choice to go against the avoidance of use requested by the ICRC.

**Comment by quincylvania** [comment]
Note that only the *red* cross is a protected symbol of the Red Cross organizations. A cross is still a [generic first aid symbol](https://en.wikipedia.org/wiki/ISO_7010). iD doesn't use the red color so it should be okay.

My bigger concern is making sure the icons aren't region- or faith-specific. The Star of Life is used more for ambulatory services than generic healthcare, but it still might be an improvement. We can reduce cultural ambiguity by using literal icons where possible rather than these abstract symbols.

**Comment by quincylvania** [comment]
I didn't add an asterisk version for vending_medicine yet since I don't think iD uses that icon and I doubt the asterisk would be very readable at that size.

**Comment by quincylvania** [comment]
Here are the new icons by the way.

<img width="548" alt="Screen Shot 2021-01-05 at 9 20 54 AM" src="https://user-images.githubusercontent.com/2046746/103657068-6880d000-4f37-11eb-9107-11c70276aeb5.png">

**Comment by 1ec5** [comment]
The Star of Life might not be recognizable as such without the Rod of Asclepius or a simplified variant inside. For example, `briefcase_asterisk` could be misinterpreted as a “miscellaneous office”, `mountain_asterisk` looks like a ❄️ snowy mountain, and the asterisk inside the vending machine could be misinterpreted as an indication that the vending machine has stuff inside it. Unfortunately, placing even a simplified Rod of Asclepius inside the star would make the star indiscernible at the smallest size.

**Comment by ArloJamesBarnes** [comment]
What about just the rod? I've seen iconic versions with what looks like a superimposed s, |, and z; that's about as little detail as I think you could get away with and still have it be recognisable.
