### ISSUE TITLE
milk churn stand

### ISSUE THREAD

**Issue by b-unicycling** [ideditor/temaki#84]
We're working on a preset for iD for milk churn stands to make it easier for beginners to map them.
I had already come up with one for `historic=creamery` (in a different colour) which was never used, so we can use that, as documented on the [wiki page](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmilk_churn_stand).

#https://github.com/openstreetmap/id-tagging-schema/issues/869

**Comment by tyrasd** [comment]
I just noticed that the icon from the wiki ([![](https://wiki.openstreetmap.org/w/images/8/84/Milk_churn_stand.svg)](https://wiki.openstreetmap.org/w/images/8/84/Milk_churn_stand.svg)) is unfortunately not a proper vector graphic, but instead just a png wrapped inside an svg file. That would mean that the icon would need to be vectorized first. Alternatively, we could look out for a suitable alternative on https://www.svgrepo.com perhaps.

**Comment by bhousel** [comment]
> Thanks! 🥇 There I was wasting my time on it...Should have refreshed the page here instead.

haha yeah, I've gotten pretty quick at drawing these things 😁

**Comment by bhousel** [comment]
Sure I can release it now - I usually wait a little while in case other icon requests come in.
